### ISSUE TITLE
issue : deprecated mongoose promises

### ISSUE THREAD

**Issue by kurdi89** [DanWahlin/NodeExpressMongoDBDockerApp#1]
`(node:12684) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
connection error: { MongoError: failed to connect to server [mongodb:27017] on first connect [MongoError: getaddrinfo ENOTFOUND mongodb mongodb:27017]
    at Pool.<anonymous> (C:\Dev\NodeExpressMongoDBDockerApp\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (C:\Dev\NodeExpressMongoDBDockerApp\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (C:\Dev\NodeExpressMongoDBDockerApp\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'MongoError',
  message:
   'failed to connect to server [mongodb:27017] on first connect [MongoError: getaddrinfo ENOTFOUND mongodb mongodb:27017]' }`

**Comment by DanWahlin** [comment]
Yeah - not an error - just a deprecation warning on the first part.

For the second part, that makes it look like it couldn't find your MongoDB server (ENOTFOUND error). It's hard for me to say what the problem is there so I'd go back through the readme and make sure you're following all of the steps.
