### ISSUE TITLE
Mongoose TS error

### ISSUE THREAD

**Issue by aron98** [DanWahlin/NodeExpressMongoDBDockerApp#18]
Nodeapp fails on start with the error given here:

```
nodeapp  |
nodeapp  | > expressite@1.0.0 start
nodeapp  | > node server.js
nodeapp  |
nodeapp  | /var/www/node_modules/mongoose/lib/cursor/QueryCursor.js:137
nodeapp  | QueryCursor.prototype.map = function(fn) {
nodeapp  |                           ^
nodeapp  |
nodeapp  | TypeError: Cannot assign to read only property 'map' of object '#<QueryCursor>'
nodeapp  |     at Object.<anonymous> (/var/www/node_modules/mongoose/lib/cursor/QueryCursor.js:137:27)
nodeapp  |     at Module._compile (node:internal/modules/cjs/loader:1097:14)
nodeapp  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
nodeapp  |     at Module.load (node:internal/modules/cjs/loader:975:32)
nodeapp  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
nodeapp  |     at Module.require (node:internal/modules/cjs/loader:999:19)
nodeapp  |     at require (node:internal/modules/cjs/helpers:102:18)
nodeapp  |     at Object.<anonymous> (/var/www/node_modules/mongoose/lib/query.js:12:21)
nodeapp  |     at Module._compile (node:internal/modules/cjs/loader:1097:14)
nodeapp  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
nodeapp  |     at Module.load (node:internal/modules/cjs/loader:975:32)
nodeapp  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
nodeapp  |     at Module.require (node:internal/modules/cjs/loader:999:19)
nodeapp  |     at require (node:internal/modules/cjs/helpers:102:18)
nodeapp  |     at Object.<anonymous> (/var/www/node_modules/mongoose/lib/index.js:26:15)
nodeapp  |     at Module._compile (node:internal/modules/cjs/loader:1097:14)
nodeapp  |
nodeapp  | Node.js v17.5.0
nodeapp exited with code 1
```

**Comment by aron98** [comment]
#19 fixes this issue

**Comment by DanWahlin** [comment]
Thanks @aron98! My guess is a Dependabot PR (tons came in recently) broke something this time around (normally they don't mess anything up - at least I haven't hit that in the past). I'll take a look at your PR. Thanks for making time to submit that! Really appreciate it.

UPDATE: Nope - not a dependabot issue - see comment below though about a mongoose update.

**Comment by DanWahlin** [comment]
As a heads-up it looks like the latest version of mongoose fixes the issue as well. Really appreciate the PR though!
